name: Build and deploy web

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the "builder" Docker image
      run: docker build . --file builder/Dockerfile --tag kanjiexplorer-builder:latest

    - name: Generate JSON and SVG from Taka
      run: |
        docker run \
        -v ${{ github.workspace }}/takadb:/taka -v ${{ github.workspace }}/web:/web \
        kanjiexplorer-builder /builder/taka_to_web.sh /taka /web

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages
        folder: web
